# Generated by Django 2.1.2 on 2018-12-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181215_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_producto',
            name='fecha_valorizacion',
            field=models.CharField(max_length=10),
        ),
    ]
