# Generated by Django 2.1.2 on 2018-12-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181215_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_lista',
            name='id_lista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Lista'),
            preserve_default=False,
        ),
    ]
